openapi: 3.0.1
info:
  title: Expatrio Jerin
  description: Open API spec for Expatrio
  contact:
    email: jerinignatious1998@gmail.com
  version: v1
paths:
  /expatrio/v1/users:
    get:
  /expatrio/v1/user:
    post:
    put:
    delete:
