openapi: 3.0.1
info:
  title: Expatrio Jerin
  description: Open API spec for Expatrio
  contact:
    email: jerinignatious1998@gmail.com
  version: v1
paths:
  /expatrio/v1/users:
    get:
      tags:
        - users
      summary: returns a list of all users with a given role
      operationId: getAllUsers
      parameters:
        - $ref: "#/components/parameters/userRole"
      responses:
        "200":
          description: User request is successfully registered
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetAllUsersResponse"
#  /expatrio/v1/user:
#    post:
#    put:
#    delete:
components:
  parameters:
    userId:
      in: header
      name: x-user-id
      required: true
      schema:
        type: string
    userRole:
      in: query
      name: userRole
      required: true
      schema:
        $ref: "#/components/schemas/UserRoles"
  schemas:
    UserRoles:
      type: string
      enum:
        - ADMIN
        - CUSTOMER
    GetAllUsersResponse:
      type: object
      required:
        - userAttributes
      properties:
        userAttributes:
          type: array
          items:
            $ref: "#/components/schemas/UserAttributes"
    UserAttributes:
      type: object
      required:
        - userId
        - userRole
      properties:
        userId:
          type: object
        userRole:
          $ref: "#/components/schemas/UserRoles"
